version: "3"
virtualmachines:
- name: workstation
  image: instruqt-hashicorp/tfc-workstation-1-1-4
  shell: /bin/bash -l
  machine_type: n1-standard-1
containers:
- name: cloud-client
  image: gcr.io/instruqt/cloud-client
  ports: [80]
  shell: /bin/bash
- name: hashiwrkst
  image: gcr.io/instruqt-hashicorp/hashiworkstation:vsc
  shell: /bin/bash
  memory: 256
- name: labclient
  image: gcr.io/instruqt-hashicorp/lab-client:1.9.2
  shell: /bin/bash
  memory: 256
- name: vscclient
  image: gcr.io/instruqt-hashicorp/vsc:latest
  shell: /bin/bash
  memory: 256
aws_accounts:
- name: TF-WORKSHOP
  managed_policies:
  - arn:aws:iam::aws:policy/AdministratorAccess