version: "3"
containers:
- name: cloud-client
  image: gcr.io/instruqt/cloud-client
  shell: /bin/bash
  ports:
  - 80
- name: vault-ent
  image: gcr.io/instruqt-hashicorp/hashiworkstation:vsc
  shell: /bin/bash
  memory: 256
- name: vault-hsm
  image: gcr.io/instruqt-hashicorp/hashiworkstation:vsc
  shell: /bin/bash
  memory: 256
virtualmachines:
- name: workstation
  image: instruqt-hashicorp/tfc-workstation-1-1-4
  shell: /bin/bash -l
  machine_type: n1-standard-1
aws_accounts:
- name: TF-WORKSHOP
  managed_policies:
  - arn:aws:iam::aws:policy/AdministratorAccess
